var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.findInternal=function(b,f,d){b instanceof String&&(b=String(b));for(var h=b.length,g=0;g<h;g++){var l=b[g];if(f.call(d,l,g,b))return{i:g,v:l}}return{i:-1,v:void 0}};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(b,f,d){b!=Array.prototype&&b!=Object.prototype&&(b[f]=d.value)};
$jscomp.getGlobal=function(b){return"undefined"!=typeof window&&window===b?b:"undefined"!=typeof global&&null!=global?global:b};$jscomp.global=$jscomp.getGlobal(this);$jscomp.polyfill=function(b,f,d,h){if(f){d=$jscomp.global;b=b.split(".");for(h=0;h<b.length-1;h++){var g=b[h];g in d||(d[g]={});d=d[g]}b=b[b.length-1];h=d[b];f=f(h);f!=h&&null!=f&&$jscomp.defineProperty(d,b,{configurable:!0,writable:!0,value:f})}};
$jscomp.polyfill("Array.prototype.findIndex",function(b){return b?b:function(b,d){return $jscomp.findInternal(this,b,d).i}},"es6","es3");$jscomp.polyfill("Array.prototype.find",function(b){return b?b:function(b,d){return $jscomp.findInternal(this,b,d).v}},"es6","es3");$jscomp.polyfill("Object.is",function(b){return b?b:function(b,d){return b===d?0!==b||1/b===1/d:b!==b&&d!==d}},"es6","es3");
$jscomp.polyfill("Array.prototype.includes",function(b){return b?b:function(b,d){var f=this;f instanceof String&&(f=String(f));var g=f.length;d=d||0;for(0>d&&(d=Math.max(d+g,0));d<g;d++){var l=f[d];if(l===b||Object.is(l,b))return!0}return!1}},"es7","es3");
$jscomp.checkStringArgs=function(b,f,d){if(null==b)throw new TypeError("The 'this' value for String.prototype."+d+" must not be null or undefined");if(f instanceof RegExp)throw new TypeError("First argument to String.prototype."+d+" must not be a regular expression");return b+""};$jscomp.polyfill("String.prototype.includes",function(b){return b?b:function(b,d){return-1!==$jscomp.checkStringArgs(this,b,"includes").indexOf(b,d||0)}},"es6","es3");
$(function(){function b(a,c,b){var e=document.querySelectorAll("."+c+"."+a);$("body").addClass("line-active");_.delay(function(){$("body").removeClass("line-active");e.forEach(F)},750);e.forEach(b?G:H)}function f(a,c){var b=c.shiftKey,d={value:0,mode:c.altKey?"auto":"manual"};d.value=a.value*("auto"===d.mode?2:1);c=void 0!==q[a.resource].shared?q[a.resource].shared:q[a.resource][a.side];var k=a;b&&(b=c,c=k,k=b);console.log("src,dest",c,k);if(k===a){if(1>c.count)return a;c.count--;k.hits.push(d)}else{b=
_.findIndex(c.hits,{mode:d.mode});if(0>b)return a;c.hits.splice(b,1);k.count++}console.log("rowData.side,rowData.scoreKey",a.side,a.scoreKey);m[a.side].resourceTargetCombos[a.scoreKey].next(a);return a}function d(a,c,e){e.preventDefault();c.hits[0]={mode:"auto",value:0};c.hits[1]={mode:"manual",value:0};var d=a.find(".points"),k=I(function(){return c.label.includes("Upper")},J,K),r=v(c.hits[0]),f=v(c.hits[1]),g=v(c),x=_.flow(w,d.text.bind(d)),h=_.flow(y,z,A,k,L,f),N=_.flow(y,z,A,k,M,r);b(c.side,c.scoreKey,
e.altKey);a.off("click").on("input","input.auto",function(a){console.log("subEvt",a);N(a);x(g(_.sum(c.hits,"value")));b(c.side,c.scoreKey,!0);m[c.side].resourceTargetCombos[c.scoreKey].next(c)}).on("input","input.manual",function(a){h(a);x(g(_.sum(c.hits,"value")));b(c.side,c.scoreKey,!1);m[c.side].resourceTargetCombos[c.scoreKey].next(c)})}function h(a,c,e){b(c.side,c.scoreKey,e.altKey);c.update(c,e);a.html(c.template(c))}function g(a){var c=_.template('\n      <div class="section <%= resource %>">\n        <p class="section-title"><%= section %></p>\n      </div>\n    '),
b=$("."+a+"-side");b.length&&(b.remove(),console.log("removing"));var d={};b=$('<div class="side '+a+'-side"></div>');var k=[],r=[];_.forEach(B,function(e){var f=e.target+"-"+e.resource,g=_.assign({},{hits:[],scoreKey:f,side:a},e);d[e.section]||(d[e.section]=$(c(g)).appendTo(b));var t=$('<div class="row '+a+" "+f+'">'+g.template(g)+"</div>").appendTo(d[e.section]);("multiplier"===e.resource?r:k).push(g);m[a].resourceTargetCombos[f]=new Rx.ReplaySubject(1);var h=$(e.svgSelectors[a]);h.toArray().forEach(function(b){["clickable",
a,f].forEach(function(a){return b.classList.add(a)})});t.on("click",function(b){g.clickHandler(t,g,b,e,a,f)});if(e.svgSelectors.left!==e.svgSelectors.right)h.off("click").on("click",function(b){g.clickHandler(t,g,b,e,a,f)});else 1===_.find(k.concat(r),{scoreKey:f}).length&&h.off("click"),h.on("click",function(b){(0<e.targetPosition.xMid-b.clientX?"left":"right")===a&&g.clickHandler(t,g,b)});m.allSubscribers.push(m[a].resourceTargetCombos[f].subscribe(function(){var b=0,c=0,e=0,d=0;_.forEach(r,function(a){return _.forEach(a.hits,
function(a){"auto"===a.mode?e+=a.value:d+=a.value})});_.forEach(k,function(a){return _.forEach(a.hits,function(a){"auto"===a.mode?b+=a.value:c+=a.value})});m[a].score.next(b*e+c*d)}))});w;O;var f=$(".score-"+a),g=_.flow(w,function(a){f.text(a)});m.allSubscribers.push(m[a].score.subscribe(g));$("body").append(b)}function l(a,b){_.forEach(B,function(c){var d=c.target+"-"+c.resource;c.targetCollection=$(c.svgSelectors[a]);c.sectionCollection=$("."+a+"-side .section."+c.resource);var e=c.sectionCollection.find(".row."+
d+"."+a+" .row-label");c.svgSelectors[a]&&0!==c.targetCollection.length&&0!==c.sectionCollection.length&&(c.targetPosition=C(c.targetCollection),c.sectionPosition=C(e),e={},e.x1=c.sectionPosition.x2+5,e.y1=c.sectionPosition.y2-10,e.x2=c.targetPosition.xMid,e.y2=c.targetPosition.yMid,"right"===a&&(e.x1=c.targetPosition.xMid,e.y1=c.targetPosition.yMid,e.x2=c.sectionPosition.x1-5,e.y2=c.sectionPosition.y2-10),e.class=d+" "+a,d3.select(b).append("line").attr(e))})}function C(a){var c,b,d,f;a=$(a).toArray();
a=_.reduce(a,function(a,e){f=d=b=c=void 0;e=e.getBoundingClientRect();c=Math.round(e.left);b=Math.round(e.top);d=Math.round(e.right);f=Math.round(e.bottom);a.x1>c&&(a.x1=c);a.x2<d&&(a.x2=d);a.y1>b&&(a.y1=b);a.y2<f&&(a.y2=f);return a},{x1:Infinity,y1:Infinity,x2:-Infinity,y2:-Infinity});a.width=Math.round(a.x2-a.x1);a.xMid=Math.floor(a.x1+a.width/2);a.height=Math.round(a.y2-a.y1);a.yMid=Math.floor(a.y1+a.height/2);return a}function D(){q={vader:{shared:{count:1},template:p.circle},stormTrooper:{shared:{count:10},
template:p.circle},cantina:{shared:{count:1},template:p.circle},thrusters:{left:{count:1E4},right:{count:1E4}},multiplier:{left:{count:1},right:{count:1}},carbonite:{left:{count:1},right:{count:1},template:p.circle}}}var n=function(a,c){c=void 0===c?Math.round:c;var b=Math.pow(10,void 0===a?0:a);return function(a){return c(a*b)/b}},w=n(1),O=n(0);n=function(a){return function(b){return function(c){return b.forEach(function(b){c.classList[a](b)})}}};var F=n("remove")(["active","auto","manual"]),G=n("add")(["active",
"auto"]),H=n("add")(["active","manual"]);n=function(a){return a*a};var E=function(a){return function(b){return b/a}},J=_.flow(n,E(2)),K=_.flow(n,E(3)),I=function(a,b,d){return function(c){return a(c)?b(c):d(c)}},L=_.identity,M=function(a){return function(b){return a*b}}(2),A=function(a){return 25<a?25:a},z=function(a){return+(a.replace(/[^\d\.]/g,"")||0)},y=function(a){return a.target.value},v=function(a){return function(b){return a.value=b}},m={allSubscribers:[],left:{resourceTargetCombos:{},score:new Rx.BehaviorSubject(0)},
right:{resourceTargetCombos:{},score:new Rx.BehaviorSubject(0)}},p={circle:function(){return'<svg><circle class="<%= hit.mode %> cannonball" cx="5" cy="9" r="5"/></svg>'},lantern:function(){return'<svg><path class="<%= hit.mode %> lantern" d="M1,4 9,4 9,13 1,13 Z M0,3 5,0 10,3 10,18 0,18 Z" style="fill-rule:evenodd" /></svg>'},flag:function(){return'<svg style="width:20px;height:10px;"><path class="<%= hit.mode %> flag" d="M0,0 20,5 0,10 Z" /></svg>'},lopsidedDiamond:function(){return'<svg style="width:10px;"><path class="<%= hit.mode %> teabag" d="M4,0 10,10 6,18 0,8 Z" /></svg>'},
multiplierRow:function(a){return'\n      <div class="row-label">'+a.label+'</div>\n      <div class="points"><span class="auto"><%= hits[0].value %>x</span> | <span class="manual"><%= hits[1].value %>x</span></div>'},defaultRow:function(a){return'\n      <div class="row-label">'+a.label+'</div>\n      <div class="tally"><% _.forEach(hits,(hit)=>{ %>'+q[a.resource].template()+"<% }) %></div>\n      <div class=\"points\"><%= _.sum(hits,'value') %></div>"},thrusterRow:function(a){return'\n      <div class="row-label">'+
a.label+'</div>\n      <div class="tally">\n        <input class="auto" type="text" value="<% (hits[0]||{}).value %>"/>\n        <input class="manual" type="text" value="<% (hits[1]||{}).value %>"/>\n      </div>\n      <div class="points"><%= _.sum(hits,\'value\') %></div>'}},q;D();var B=[{target:"multiplier",label:"LightSaber",section:"Multiplier",resource:"multiplier",value:1,cycle:[1,1.5,2,2.5,3],hits:[{mode:"auto",value:1},{mode:"manual",value:1}],svgSelectors:{left:"#lightSaberLeft",right:"#lightSaberRight"},
update:function(a,b){var c=b.altKey?a.hits[0]:a.hits[1];b=a.cycle.indexOf(c.value)+(b.shiftKey?-1:1);0>b?b=0:b>=a.cycle.length&&(b=a.cycle.length-1);c.value=a.cycle[b];m[a.side].resourceTargetCombos[a.scoreKey].next(a);return a},template:p.multiplierRow},{target:"vaderSaber",label:"LightSaber",section:"Vader Capture",resource:"vader",value:51,svgSelectors:{left:"#vaderSaber",right:"#vaderSaber"}},{target:"vaderNoSaber",label:"No LightSaber",section:"Vader Capture",resource:"vader",value:25,svgSelectors:{left:"#vader",
right:"#vader"}},{target:"dstarShelf",label:"Death Star Bay",section:"Storm Trooper Placement",resource:"stormTrooper",value:45,svgSelectors:{left:"#dstarShelf",right:"#dstarShelf"}},{target:"upperLaser",label:"KX9 Laser Upper",section:"Storm Trooper Placement",resource:"stormTrooper",value:21,svgSelectors:{left:"#upperLaserLeft",right:"#upperLaserRight"}},{target:"upperWing",label:"Wing Upper",section:"Storm Trooper Placement",resource:"stormTrooper",value:19,svgSelectors:{left:"#upperWingLeft",
right:"#upperWingRight"}},{target:"lowerLaser",label:"KX9 Laser Lower",section:"Storm Trooper Placement",resource:"stormTrooper",value:13,svgSelectors:{left:"#lowerLaserLeft",right:"#lowerLaserRight"}},{target:"lowerWing",label:"Wing Lower",section:"Storm Trooper Placement",resource:"stormTrooper",value:11,svgSelectors:{left:"#lowerWingLeft",right:"#lowerWingRight"}},{target:"compactor",label:"Trash Compactor",section:"Storm Trooper Placement",resource:"stormTrooper",value:5,svgSelectors:{left:"#compactorLeft",
right:"#compactorRight"}},{target:"cantina",label:"Cantina Bonus",section:"Mos Eisley",resource:"cantina",method:"add",value:23,svgSelectors:{left:"#cantinaLeft",right:"#cantinaRight"}},{target:"upperThruster",label:"Upper",section:"Thrusters",resource:"thrusters",value:312,svgSelectors:{left:"#upperThrusterLeft",right:"#upperThrusterRight"},template:p.thrusterRow,clickHandler:d},{target:"lowerThruster",label:"Lower",section:"Thrusters",resource:"thrusters",value:208,svgSelectors:{left:"#lowerThrusterLeft",
right:"#lowerThrusterRight"},template:p.thrusterRow,clickHandler:d},{target:"carbonite4",label:"Mark 4",section:"Carbonite Lift",resource:"carbonite",value:44,svgSelectors:{left:"#carbonite4Left",right:"#carbonite4Right"}},{target:"carbonite3",label:"Mark 3",section:"Carbonite Lift",resource:"carbonite",value:34,svgSelectors:{left:"#carbonite3Left",right:"#carbonite3Right"}},{target:"carbonite2",label:"Mark 2",section:"Carbonite Lift",resource:"carbonite",value:23,svgSelectors:{left:"#carbonite2Left",
right:"#carbonite2Right"}},{target:"carbonite1",label:"Mark 1",section:"Carbonite Lift",resource:"carbonite",value:11,svgSelectors:{left:"#carbonite1Left",right:"#carbonite1Right"}}].map(function(a){a.template=_.template((a.template||p.defaultRow)(a));a.update||(a.update=f);a.clickHandler||(a.clickHandler=h);return a}),u=$("div.help");$("body").on("keyup",function(a){27===a.which&&u.hide();a.shiftKey&&191===a.which&&u.toggle()});u.find(".close").on("click",function(){return u.hide()});(function(){function a(){_.invoke(m.allSubscribers,
"unsubscribe");g("left");g("right");D();for(var a=$(".section.multiplier .row"),b=5;--b;)a.trigger({type:"click",shiftKey:!0}),a.trigger({type:"click",shiftKey:!0,altKey:!0});m.left.score.next(0);m.right.score.next(0);h=k}function b(){var a=k-h;k=120===k?90:120;h=k-a}function d(a){f.html(a)}var f=$(".timer"),k=120,h=k,l=null;d(h);f.on("click",function(c){c.shiftKey&&a();c.altKey&&b();c.shiftKey||c.altKey||l?(d(h),l&&l.unsubscribe(d),l=null):l=Rx.Observable.timer(0,1E3).filter(function(){return 0<
h}).map(function(){return--h}).subscribe(d)})})();g("left");g("right");l("left",".linecontainer");l("right",".linecontainer");$(window).on("resize",_.debounce(function(){$(".linecontainer").empty();l("left",".linecontainer");l("right",".linecontainer")},500))}());